version: '3.1'

services:
  db:
    image: postgres:14.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD : root
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: