apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
stringData:
  VIDEOS_MONGO_URI: mongodb://root:root@host.minikube.internal:27017/videos?authSource=admin
  MP3S_MONGO_URI: mongodb://root:root@host.minikube.internal:27017/mp3s?authSource=admin
  RABBITMQ: "rabbitmq"
