apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root
  JWT_SECRET: tkqs91PbuVhyu13yW6n+Yhkds+fRr90+9xxEaiZSzX6uaYPUojBSV1vxTTE2sS1ljTi+cDQTKrloUzzMoWuboA==

